steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace/repository-name/Ang-Test-Repo'

  # Step 2: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build-prod']
    dir: '/workspace/repository-name/Ang-Test-Repo'
  
  # Step 3: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/repository-name/Ang-Test-Repo/dist/*'
      - 'gs://ang-test-bucket/build-artifacts/'

timeout: '1200s'

artifacts:
  objects:
    location: 'gs://ang-test-bucket/build-artifacts/'
    paths:
      - '/workspace/repository-name/Ang-Test-Repo/dist/**'

options:
  logging: 'CLOUD_LOGGING_ONLY'
