steps:
  # Step 1: Install the latest version of npm globally
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install', '-g', 'npm@latest']

  # Step 2: Delete the existing package-lock.json and node_modules directory
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        rm -rf package-lock.json node_modules

  # Step 3: Install dependencies and generate a new package-lock.json
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Step 5: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build-prod']

  # Step 6: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/Ang-Test-Repo/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

options:
  logging: 'CLOUD_LOGGING_ONLY'
