steps:
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '.'

  Upload the build output to Google Cloud Storage
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'gsutil'
    args: ['cp', '-r', 'dist/Ang-Test-Repo/*', 'gs://ang-test-bucket']
    dir: '.'

timeout: '1200s'
options:
  logging: 'CLOUD_LOGGING_ONLY'
