steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  # Step 2: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build-prod']
    dir: '.'

  # Debugging Step: List contents of the workspace directory
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "Listing contents of /workspace/repository-name/Ang-Test-Repo"
          ls -l /home/ubuntu/Angular-Projects/Ang-Test-Repo/dist/* || echo "Directory does not exist or is empty"

  # Step 3: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/home/ubuntu/Angular-Projects/Ang-Test-Repo/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

artifacts:
  objects:
    location: 'gs://ang-test-bucket/build-artifacts/'
    paths:
      - '/home/ubuntu/Angular-Projects/Ang-Test-Repo/dist/*'

options:
  logging: 'CLOUD_LOGGING_ONLY'
