steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace/repository-name'

  # Step 2: Build the Angular project
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '/workspace/repository-name'

  # Step 3: Upload the build output to Google Cloud Storage
gsutil -m cp -r D:\Angular Projects\Ang-Test-Repo\* gs://ang-test-bucket


timeout: '1200s'
options:
  logging: 'CLOUD_LOGGING_ONLY'
