steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace/Ang-Test-Repo'

  # Step 2: Build the Angular app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '/workspace/Ang-Test-Repo'

  # Debug: List contents of the workspace after build
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "Listing contents of workspace after build"
          echo "Testing Path"
          ls -la
          echo "Exising Code"
          ls -R /workspace/Ang-Test-Repo

  # Step 3: Verify if the dist directory exists
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "Checking if dist directory exists"
          if [ -d /workspace/Ang-Test-Repo/dist ]; then
            echo "Directory exists"
          else
            echo "Directory does not exist"
          fi

  # Step 4: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/Ang-Test-Repo/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

options:
  logging: 'CLOUD_LOGGING_ONLY'