steps:
  # Step 1: Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace'

  # Step 2: Build the Angular app
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '/workspace'

  # Step 3: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

options:
  logging: 'CLOUD_LOGGING_ONLY'
