steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace/repository-name/Ang-Test-Repo'

  # Step 2: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build-prod']
    dir: '/workspace/repository-name/Ang-Test-Repo'

  # Step 3: Verify contents of build directory
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Checking contents of dist directory"
        ls -l /workspace/repository-name/Ang-Test-Repo/dist || echo "Directory does not exist or is empty"

# Upload a specific file to verify gsutil works
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
  entrypoint: 'gsutil'
  args: ['cp', '/workspace/repository-name/Ang-Test-Repo/dist/index.html', 'gs://ang-test-bucket']


timeout: '1200s'


options:
  logging: 'CLOUD_LOGGING_ONLY'
