steps:
  # Step 1: Install dependencies and run audit fix
  - name: 'node:18'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Installing dependencies..."
        npm install
        echo "Running npm audit fix..."
        npm audit fix

  # Step 2: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '/workspace'

  # Step 3: Upload build artifacts to Google Cloud Storages
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

options:
  logging: 'CLOUD_LOGGING_ONLY'
