steps:
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['install']
    dir: '.'

  - name: 'node:16'
    entrypoint: 'npm'
    args: ['run', 'build']
    dir: '.'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'gsutil'
    args: ['-m', 'rsync', '-r', 'dist/Ang-Test-Repo/', 'gs://ang-test-bucket']
    dir: '.'

timeout: '1200s'
options:
  logging: 'GCS_ONLY'
  logs_bucket: 'gs://your-logs-bucket'
