steps:
  # Step 1: Install dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']
    dir: '/workspace/Ang-Test-Repo'

  # Step 2: Build the Angular app
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build-prod']
    dir: '/workspace/Ang-Test-Repo'
  
  # Step 3: Verify contents of the dist directory
  - name: 'alpine:latest'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
          echo "Checking contents of dist directory"
          ls -l /workspace/Ang-Test-Repo/dist || echo "Directory does not exist or is empty"

  # Step 4: Upload build artifacts to Google Cloud Storage
  - name: 'gcr.io/cloud-builders/gsutil'
    args:
      - '-m'
      - 'cp'
      - '-r'
      - '/workspace/Ang-Test-Repo/dist/*'
      - 'gs://ang-test-bucket/'

timeout: '1200s'

artifacts:
  objects:
    location: 'gs://ang-test-bucket/'
    paths:
      - '**/*'

options:
  logging: 'CLOUD_LOGGING_ONLY'
